# Copyright Amazon.com, Inc. or its affiliates. All Rights Reserved.
# SPDX-License-Identifier: Apache-2.0

[workspace]

[package]
name = "gg-log-manager"
version = "0.1.0"
edition = "2021"
description = "Greengrass LogManager - Generic type component for log and EMF file upload to CloudWatch"
license = "Apache-2.0"

[dependencies]
tracing = "0.1"
tracing-subscriber = "0.3"

[dev-dependencies]
tempfile = "3"

[profile.release]
strip = true
lto = true
codegen-units = 1
opt-level = "z"
