---
RecipeFormatVersion: '2020-01-25'
ComponentName: aws.greengrass.LogManager
ComponentDescription: AWS Greengrass Log Manager
ComponentPublisher: AWS
ComponentVersion: '2.0.0'
ComponentType: aws.greengrass.plugin
Manifests:
    - Artifacts:
        - URI: s3://gg-dev-artifacts-$stage/$componentName/$version/aws.greengrass.LogManager.jar
