RecipeFormatVersion: "2020-01-25"
ComponentName: aws.greengrass.LogManager
ComponentVersion: "{COMPONENT_VERSION}"
ComponentType: aws.greengrass.generic
ComponentDescription: Greengrass LogManager - Generic type component for log and EMF file upload to CloudWatch
ComponentPublisher: Amazon
ComponentDependencies:
  aws.greengrass.TokenExchangeService:
    VersionRequirement: ">=0.0.0"
    DependencyType: HARD
ComponentConfiguration:
  DefaultConfiguration:
    deprecatedVersionSupport: "true"
    logsUploaderConfiguration:
      systemLogsConfiguration:
        uploadToCloudWatch: "false"
        minimumLogLevel: "INFO"
      componentLogsConfigurationMap: {}
    periodicUploadIntervalSec: "300"
Manifests:
  - Platform:
      os: linux
      architecture: amd64
      runtime: "*"
    Artifacts:
      - URI: s3://gg-components/gg-log-manager-{COMPONENT_VERSION}-linux-amd64
        Permission:
          Execute: OWNER
    Lifecycle:
      Setenv:
        GG_LOG_MANAGER_CONFIG: "{configuration:/}"
      run: "{artifacts:path}/gg-log-manager-{COMPONENT_VERSION}-linux-amd64 --work-dir {work:path}"
  - Platform:
      os: linux
      architecture: aarch64
      runtime: "*"
    Artifacts:
      - URI: s3://gg-components/gg-log-manager-{COMPONENT_VERSION}-linux-aarch64
        Permission:
          Execute: OWNER
    Lifecycle:
      Setenv:
        GG_LOG_MANAGER_CONFIG: "{configuration:/}"
      run: "{artifacts:path}/gg-log-manager-{COMPONENT_VERSION}-linux-aarch64 --work-dir {work:path}"
  - Platform:
      os: linux
      architecture: aarch64
      architecture.detail: armv8l
      runtime: "*"
    Artifacts:
      - URI: s3://gg-components/gg-log-manager-{COMPONENT_VERSION}-linux-aarch64
        Permission:
          Execute: OWNER
    Lifecycle:
      Setenv:
        GG_LOG_MANAGER_CONFIG: "{configuration:/}"
      run: "{artifacts:path}/gg-log-manager-{COMPONENT_VERSION}-linux-aarch64 --work-dir {work:path}"
  - Platform:
      os: windows
      architecture: amd64
    Artifacts:
      - URI: s3://gg-components/gg-log-manager-{COMPONENT_VERSION}-windows-amd64.exe
    Lifecycle:
      Setenv:
        GG_LOG_MANAGER_CONFIG: "{configuration:/}"
      run: "{artifacts:path}/gg-log-manager-{COMPONENT_VERSION}-windows-amd64.exe --work-dir {work:path}"
