---
RecipeFormatVersion: '2020-01-25'
ComponentName: '{COMPONENT_NAME}'
ComponentDescription: AWS Greengrass Log Manager
ComponentPublisher: AWS
ComponentVersion: '{COMPONENT_VERSION}'
ComponentType: aws.greengrass.plugin
Manifests:
    - Artifacts:
        - URI: s3://gg-dev-artifacts-$stage/$componentName/$version/LogManager.jar
