---
templateVersion: '2020-01-25'
componentName: aws.greengrass.log.manager
description: AWS Greengrass Log Manager
publisher: AWS
version: '0.0.0'
componentType: plugin
manifests:
  - platform:
      os: linux
    parameters:
    artifacts:
      - uri: s3://gg-dev-artifacts/$componentName/$platform.os/$version/aws.greengrass.log.manager.jar
