---
RecipeFormatVersion: '2020-01-25'
ComponentName: aws.greengrass.logmanager
ComponentDescription: AWS Greengrass Log Manager
ComponentPublisher: AWS
ComponentVersion: '0.0.0'
ComponentType: plugin
Manifests:
    - Artifacts:
        - URI: s3://gg-dev-artifacts/$componentName/$version/aws.greengrass.logmanager.jar
