---
services:
  aws.greengrass.LogManager:
    configuration:
      periodicUploadIntervalSec: 10
      logsUploaderConfiguration:
        componentLogsConfiguration:
          - componentName: 'UserComponentB'
            logFileRegex: '\w*UserComponentB\w*.\w*'
            logFileDirectoryPath: '{{logFileDirectoryPath}}'
            minimumLogLevel: 'INFO'
            diskSpaceLimit: '25'
            diskSpaceLimitUnit: 'MB'
            deleteLogFileAfterCloudUpload: 'true'
  main:
    lifecycle:
      install:
        all: echo All installed
    dependencies:
      - aws.greengrass.LogManager
