#
# Copyright Amazon.com, Inc. or its affiliates. All Rights Reserved.
# SPDX-License-Identifier: Apache-2.0
#

version: 0.2
phases:
  install:
    runtime-versions:
      java: corretto11
  build:
    commands:
      - mvn -U -ntp clean verify -f uat/pom.xml
      - mvn -U -ntp verify -DskipTests=true
      - java -Dggc.archive=./target/aws.greengrass.nucleus.zip
        -Dtags=smoke -Dggc.install.root=$CODEBUILD_SRC_DIR -Dggc.log.level=INFO -Daws.region=us-west-2
        -jar uat/testing-features/target/greengrass-log-manager-testing-features

artifacts:
  files:
    - 'testResults/**/*'
  name: 'NucleusUatLinuxLogs.zip'

reports:
  uat-reports:
    files:
      - "TEST-greengrass-results.xml"
    file-format: "JUNITXML"
